# Generated by Django 5.2.12 on 2026-03-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
